{{ config(severity='warn') }}

SELECT 'SV_MEETINGS' AS TABLE_NAME, MEETING_ID AS RECORD_ID, START_TIME
FROM {{ ref('sv_meetings') }}
WHERE START_TIME > CURRENT_TIMESTAMP()

UNION ALL

SELECT 'SV_WEBINARS', WEBINAR_ID, START_TIME
FROM {{ ref('sv_webinars') }}
WHERE START_TIME > CURRENT_TIMESTAMP()

UNION ALL

SELECT 'SV_FEATURE_USAGE', USAGE_ID, CAST(USAGE_DATE AS TIMESTAMP_NTZ)
FROM {{ ref('sv_feature_usage') }}
WHERE USAGE_DATE > CURRENT_DATE()
