{{ config(severity='warn') }}

SELECT MEETING_ID, DURATION_MINUTES,
       DATEDIFF('minute', START_TIME, END_TIME) AS CALCULATED_DURATION
FROM {{ ref('sv_meetings') }}
WHERE START_TIME IS NOT NULL 
  AND END_TIME IS NOT NULL 
  AND DURATION_MINUTES IS NOT NULL
  AND ABS(DURATION_MINUTES - DATEDIFF('minute', START_TIME, END_TIME)) > 1
