version: 2

models:
  - name: go_daily_meeting_summary
    description: "Daily aggregated meeting metrics by organization"
    columns:
      - name: summary_id
        description: "Unique ID for the daily summary"
        tests:
          - unique
          - not_null
      - name: summary_date
        description: "Date of the meetings"
        tests:
          - not_null
      - name: organization_id
        description: "Company/Organization ID"
        tests:
          - not_null
      - name: total_meetings
      - name: total_meeting_minutes
      - name: total_participants
      - name: unique_hosts
      - name: unique_participants
      - name: average_meeting_duration
      - name: average_participants_per_meeting
      - name: load_date
        tests:
          - not_null
      - name: update_date
        tests:
          - not_null
      - name: source_system

  - name: go_monthly_user_activity
    description: "Monthly aggregated user activity metrics"
    columns:
      - name: activity_id
        tests:
          - unique
          - not_null
      - name: activity_month
        tests:
          - not_null
      - name: user_id
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: meetings_hosted
      - name: meetings_attended
      - name: total_hosting_minutes
      - name: total_attendance_minutes
      - name: load_date
        tests:
          - not_null
      - name: update_date
        tests:
          - not_null
      - name: source_system

  - name: go_feature_adoption_summary
    description: "Feature usage and adoption summary"
    columns:
      - name: adoption_id
        tests:
          - unique
          - not_null
      - name: summary_period
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: feature_name
        tests:
          - not_null
      - name: total_usage_count
      - name: unique_users_count
      - name: load_date
        tests:
          - not_null
      - name: update_date
        tests:
          - not_null
      - name: source_system

  - name: go_quality_metrics_summary
    description: "Aggregated meeting quality metrics"
    columns:
      - name: quality_summary_id
        tests:
          - unique
          - not_null
      - name: summary_date
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: total_sessions
      - name: average_audio_quality
      - name: average_video_quality
      - name: connection_success_rate
      - name: call_drop_rate
      - name: load_date
        tests:
          - not_null
      - name: update_date
        tests:
          - not_null
      - name: source_system

  - name: go_engagement_summary
    description: "Aggregated engagement metrics"
    columns:
      - name: engagement_id
        tests:
          - unique
          - not_null
      - name: summary_date
        tests:
          - not_null
      - name: organization_id
        tests:
          - not_null
      - name: total_meetings
      - name: total_chat_messages
      - name: screen_share_sessions
      - name: total_reactions
      - name: qa_interactions
      - name: poll_responses
      - name: average_attention_score
      - name: load_date
        tests:
          - not_null
      - name: update_date
        tests:
          - not_null
      - name: source_system
