version: 2

models:
  - name: go_daily_meeting_summary
    description: "Daily aggregated meeting metrics by organization"
    columns:
      - name: SUMMARY_ID
        description: "Unique identifier for daily summary"
        tests:
          - unique
          - not_null
      - name: SUMMARY_DATE
        description: "Date of the summary"
        tests:
          - not_null
      - name: ORGANIZATION_ID
        description: "Organization identifier"
        tests:
          - not_null
      - name: TOTAL_MEETINGS
        description: "Total number of meetings"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_MEETING_MINUTES
        description: "Total meeting minutes"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_PARTICIPANTS
        description: "Total participants in meetings"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: UNIQUE_HOSTS
        description: "Unique hosts in meetings"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: UNIQUE_PARTICIPANTS
        description: "Unique participants"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: AVERAGE_MEETING_DURATION
        description: "Average meeting duration in minutes"
          

      - name: AVERAGE_PARTICIPANTS_PER_MEETING
        description: "Average participants per meeting"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: LOAD_DATE
        description: "Load date"
        tests:
          - not_null
      - name: UPDATE_DATE
        description: "Update timestamp"
        tests:
          - not_null
      - name: SOURCE_SYSTEM
        description: "Source system of data"
        

  - name: go_engagement_summary
    description: "Engagement metrics by date and organization"
    columns:
      - name: ENGAGEMENT_ID
        description: "Unique identifier for engagement summary"
        tests:
          - unique
          - not_null
      - name: SUMMARY_DATE
        description: "Summary date"
        tests:
          - not_null
      - name: ORGANIZATION_ID
        description: "Organization identifier"
        tests:
          - not_null
      - name: TOTAL_MEETINGS
        description: "Total meetings"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_CHAT_MESSAGES
        description: "Total chat messages"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: SCREEN_SHARE_SESSIONS
        description: "Screen share sessions"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_REACTIONS
        description: "Total reactions"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: QA_INTERACTIONS
        description: "Q&A interactions"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: POLL_RESPONSES
        description: "Poll responses"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: AVERAGE_ATTENTION_SCORE
        description: "Average attention score"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: LOAD_DATE
        description: "Load date"
        tests:
          - not_null
      - name: UPDATE_DATE
        description: "Update timestamp"
        tests:
          - not_null
      - name: SOURCE_SYSTEM
        description: "Source system of data"
        

  - name: go_feature_adoption_summary
    description: "Feature adoption metrics by organization"
    columns:
      - name: ADOPTION_ID
        description: "Unique identifier for adoption summary"
        tests:
          - unique
          - not_null
      - name: SUMMARY_PERIOD
        description: "Summary period"
        tests:
          - not_null
      - name: ORGANIZATION_ID
        description: "Organization identifier"
        tests:
          - not_null
      - name: FEATURE_NAME
        description: "Feature name"
        
      - name: TOTAL_USAGE_COUNT
        description: "Total usage count"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: UNIQUE_USERS_COUNT
        description: "Unique users count"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: LOAD_DATE
        description: "Load date"
        tests:
          - not_null
      - name: UPDATE_DATE
        description: "Update timestamp"
        tests:
          - not_null
      - name: SOURCE_SYSTEM
        description: "Source system of data"
        

  - name: go_monthly_user_activity
    description: "Monthly user activity aggregations"
    columns:
      - name: ACTIVITY_ID
        description: "Unique identifier for monthly activity"
        tests:
          - unique
          - not_null
      - name: ACTIVITY_MONTH
        description: "Month of activity"
        tests:
          - not_null
      - name: USER_ID
        description: "User identifier"
        tests:
          - not_null
          - relationships:
              to: ref('sv_users')
              field: USER_ID
      - name: ORGANIZATION_ID
        description: "Organization identifier"
        tests:
          - not_null
      - name: MEETINGS_HOSTED
        description: "Number of meetings hosted"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: MEETINGS_ATTENDED
        description: "Number of meetings attended"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_HOSTING_MINUTES
        description: "Total hosting minutes"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: TOTAL_ATTENDANCE_MINUTES
        description: "Total attendance minutes"
        tests:
          - dbt_utils.expression_is_true:
              expression: " >= 0"
      - name: LOAD_DATE
        description: "Load date"
        tests:
          - not_null
      - name: UPDATE_DATE
        description: "Update timestamp"
        tests:
          - not_null
      - name: SOURCE_SYSTEM
        description: "Source system of data"
        
