version: 2

sources:
  - name: silver
    database: ZOOM
    schema: SILVER
    tables:
      - name: sv_meetings
        description: "Raw meetings data from Zoom platform"
      - name: sv_participants
        description: "Raw participant-level data for each meeting"
      - name: sv_users
        description: "Zoom user details"
      - name: sv_webinars
        description: "Raw webinar-level data"
      - name: sv_feature_usage
        description: "Feature usage metrics for meetings and webinars"
      - name: sv_audit_log
        description: "Audit log capturing ETL process details"
