name: 'Analytics'
version: '1.0'

config-version: 2

model-paths: ["models"]
clean-targets: ["target", "dbt_modules"]
test-paths: ["tests"]


models:
  Analytics:
    bronze:
      +materialized: table
      +schema: BRONZE
      +pre-hook: "{{ bz_audit_log_start() }}"
      +post-hook: "{{ bz_audit_log_end() }}"
      +on_schema_change: 'fail'
    silver:
      +schema: 'SILVER'
      +materialized: table
      +pre-hook:
        - "{{ pre_audit_log() }}"
      +post-hook:
        - "{{ post_audit_log() }}"

    gold:
      +materialized: incremental
      +schema: GOLD
      +pre-hook: "{{ audit_log_start() }}"
      +post-hook: "{{ audit_log_end() }}"
      +cluster_by: ["load_date"]
      +on_schema_change: 'fail'
    dim:
      +materialized: incremental
      +schema: DIM
      +pre-hook: "{{ dim_audit_log_start(this.name) }}"
      +post-hook: "{{ dim_audit_log_end(this.name, 0) }}"
      +cluster_by: ["load_date"]
    fact:
      +materialized: incremental
      +schema: FACT
      +pre-hook: "{{ fact_audit_log_start(this.name) }}"
      +post-hook: "{{ fact_audit_log_end(this.name, 0) }}"
      +cluster_by: ["load_date"]
      +on_schema_change: 'fail'
flags:
  require_generic_test_arguments_property: true
  
vars:
  source_system: 'raw'
  max_data_age_days: 365
  dq_score_threshold: 0.8