version: 2

models:
  - name: go_user_dimension
    description: "Gold user dimension table"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
      - name: user_name
        tests:
          - not_null
      - name: email_address
        tests:
          - not_null
      - name: user_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['PRO', 'BASIC', 'ENTERPRISE', 'BUSINESS', 'STANDARD']
      - name: account_status
        tests:
          - not_null
      - name: license_type
      - name: department_name
      - name: job_title
      - name: time_zone
      - name: account_creation_date
      - name: last_login_date
      - name: language_preference
      - name: phone_number
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_organization_dimension
    description: "Gold organization dimension table"
    columns:
      - name: organization_id
        tests:
          - not_null
          - unique
      - name: organization_name
        tests:
          - not_null
      - name: maximum_user_limit

      - name: storage_quota_gb

      - name: industry_classification
      - name: organization_size
      - name: primary_contact_email
      - name: billing_address
      - name: account_manager_name
      - name: contract_start_date
      - name: contract_end_date
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_time_dimension
    description: "Gold time dimension table"
    columns:
      - name: date_key
        tests:
          - not_null
          - unique
      - name: year_number
      - name: quarter_number

      - name: month_number

      - name: month_name
      - name: week_number
      - name: day_of_year
      - name: day_of_month
      - name: day_of_week

      - name: day_name
      - name: is_weekend
      - name: is_holiday
      - name: fiscal_year
      - name: fiscal_quarter
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_device_dimension
    description: "Gold device dimension table"
    columns:
      - name: device_connection_id
        tests:
          - not_null
      - name: device_type
      - name: operating_system
      - name: application_version
      - name: network_connection_type
      - name: device_category
      - name: platform_family
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_geography_dimension
    description: "Gold geography dimension table"
    columns:
      - name: geography_dim_id
        tests:
          - not_null
          - unique
      - name: country_code
      - name: country_name
      - name: region_name
      - name: time_zone
      - name: continent
      - name: load_date
      - name: update_date
      - name: source_system