version: 2



models:
  - name: go_meeting_facts
    description: "Gold fact table capturing meeting metrics"
    columns:
      - name: meeting_fact_id
        description: "Unique ID for meeting fact"
        tests: [unique, not_null]
      - name: meeting_id
        description: "Meeting ID from silver layer"
        tests: [not_null]
      - name: host_id
      - name: meeting_topic
      - name: start_time
      - name: end_time
      - name: duration_minutes
      
      
      - name: breakout_room_count
      - name: chat_message_count
      - name: screen_share_count
      - name: quality_score_avg
      - name: recording_enabled
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_participant_facts
    description: "Gold fact table for participant metrics"
    columns:
      - name: participant_fact_id
        tests: [unique, not_null]
      - name: participant_id
        tests: [not_null]
      - name: meeting_id
      - name: user_id
      - name: participant_role
      - name: join_time
      - name: leave_time
      - name: attendance_duration
      - name: chat_messages_sent
      - name: screen_share_duration
      - name: device_type
      - name: geographic_location
      - name: interaction_count
      - name: connection_quality_rating
      - name: load_date
      - name: update_date
      - name: source_system
      - name: video_enabled

  - name: go_quality_facts
    description: "Gold fact table for quality metrics"
    columns:
      - name: quality_fact_id
        tests: [unique, not_null]
      - name: participant_id
      - name: meeting_id
      - name: device_connection_id
      - name: audio_quality_score
      - name: video_quality_score
      - name: connection_stability_rating
      - name: latency_ms
      - name: packet_loss_rate
      - name: cpu_usage_percentage
      - name: memory_usage_mb
      - name: bandwidth_utilization
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_billing_facts
    description: "Gold fact table for billing events"
    columns:
      - name: billing_fact_id
        tests: [unique, not_null]
      - name: meeting_fact_id
      - name: meeting_id
      - name: host_id
      - name: meeting_topic
      - name: start_time
      - name: end_time
      - name: duration_minutes
      - name: participant_count
      - name: breakout_room_count
      - name: chat_message_count
      - name: screen_share_count
      - name: quality_score_avg
      - name: recording_enabled
      - name: load_date
      - name: update_date
      - name: source_system

  - name: go_webinar_facts
    description: "Gold fact table for webinar metrics"
    columns:
      - name: webinar_fact_id
        tests: [unique, not_null]
      - name: webinar_id
      - name: host_id
      - name: webinar_topic
      - name: start_time
      - name: end_time
      - name: duration_minutes
      - name: registrants_count
      - name: actual_attendees
      - name: attendance_rate
      - name: qa_questions_count
      - name: poll_responses_count
      - name: load_date
      - name: update_date
      - name: source_system
