version: 2


models:
  - name: go_meeting_facts
    description: "Aggregated meeting facts for analytical queries."
    columns:
      - name: meeting_fact_id
        description: "Unique identifier for the meeting fact record."
        tests: [unique, not_null]
      - name: meeting_id
        description: "Meeting ID from source."
        tests: [not_null]
      - name: host_id
        description: "Host user ID."
      - name: meeting_topic
        description: "Meeting topic/title."
      - name: start_time
        description: "Meeting start timestamp in UTC."
      - name: end_time
        description: "Meeting end timestamp in UTC."
      - name: duration_minutes
        description: "Duration of the meeting in minutes."
      - name: participant_count
        description: "Number of unique participants."
      - name: max_concurrent_participants
        description: "Maximum concurrent participants."
      - name: total_attendance_minutes
        description: "Total attendance minutes for all participants."
      - name: average_attendance_duration
        description: "Average attendance duration per participant."
      - name: meeting_type
        description: "Type of meeting based on duration."
      - name: meeting_status
        description: "Status of the meeting (Completed, In Progress, Scheduled)."
      - name: recording_enabled
        description: "Indicates if recording was enabled."
      - name: screen_share_count
        description: "Number of screen sharing events."
      - name: chat_message_count
        description: "Number of chat messages."
      - name: breakout_room_count
        description: "Number of breakout room events."
      - name: quality_score_avg
        description: "Average data quality score for the meeting."
      - name: engagement_score
        description: "Composite engagement score."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."

  - name: go_participant_facts
    description: "Aggregated participant facts for analytical queries."
    columns:
      - name: participant_fact_id
        description: "Unique identifier for the participant fact record."
        tests: [unique, not_null]
      - name: meeting_id
        description: "Meeting ID."
      - name: participant_id
        description: "Participant ID."
      - name: user_id
        description: "User ID (or GUEST_USER)."
      - name: join_time
        description: "Join time in UTC."
      - name: leave_time
        description: "Leave time in UTC."
      - name: attendance_duration
        description: "Attendance duration in minutes."
      - name: participant_role
        description: "Role in the meeting (Host/Participant)."
      - name: audio_connection_type
        description: "Audio connection type."
      - name: video_enabled
        description: "Indicates if video was enabled."
      - name: screen_share_duration
        description: "Screen share duration."
      - name: chat_messages_sent
        description: "Number of chat messages sent."
      - name: interaction_count
        description: "Total interaction count."
      - name: connection_quality_rating
        description: "Connection quality rating."
      - name: device_type
        description: "Device type."
      - name: geographic_location
        description: "Geographic location."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."

  - name: go_webinar_facts
    description: "Aggregated webinar facts for analytical queries."
    columns:
      - name: webinar_fact_id
        description: "Unique identifier for the webinar fact record."
        tests: [unique, not_null]
      - name: webinar_id
        description: "Webinar ID."
      - name: host_id
        description: "Host user ID."
      - name: webinar_topic
        description: "Webinar topic/title."
      - name: start_time
        description: "Webinar start time in UTC."
      - name: end_time
        description: "Webinar end time in UTC."
      - name: duration_minutes
        description: "Duration of the webinar in minutes."
      - name: registrants_count
        description: "Number of registrants."
      - name: actual_attendees
        description: "Number of actual attendees."
      - name: attendance_rate
        description: "Attendance rate as a percentage."
      - name: max_concurrent_attendees
        description: "Maximum concurrent attendees."
      - name: qa_questions_count
        description: "Number of Q&A questions."
      - name: poll_responses_count
        description: "Number of poll responses."
      - name: engagement_score
        description: "Composite engagement score."
      - name: event_category
        description: "Event category based on duration."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."

  - name: go_billing_facts
    description: "Aggregated billing facts for analytical queries."
    columns:
      - name: billing_fact_id
        description: "Unique identifier for the billing fact record."
        tests: [unique, not_null]
      - name: event_id
        description: "Billing event ID."
      - name: user_id
        description: "User ID."
      - name: organization_id
        description: "Organization ID."
      - name: event_type
        description: "Event type."
      - name: amount
        description: "Transaction amount."
      - name: event_date
        description: "Event date."
      - name: billing_period_start
        description: "Start of billing period."
      - name: billing_period_end
        description: "End of billing period."
      - name: payment_method
        description: "Payment method."
      - name: transaction_status
        description: "Transaction status."
      - name: currency_code
        description: "Currency code."
      - name: tax_amount
        description: "Tax amount."
      - name: discount_amount
        description: "Discount amount."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."

  - name: go_usage_facts
    description: "Aggregated user usage facts for analytical queries."
    columns:
      - name: usage_fact_id
        description: "Unique identifier for the usage fact record."
        tests: [unique, not_null]
      - name: user_id
        description: "User ID."
      - name: organization_id
        description: "Organization ID."
      - name: usage_date
        description: "Usage date."
      - name: meeting_count
        description: "Number of meetings hosted."
      - name: total_meeting_minutes
        description: "Total meeting minutes."
      - name: webinar_count
        description: "Number of webinars hosted."
      - name: total_webinar_minutes
        description: "Total webinar minutes."
      - name: recording_storage_gb
        description: "Estimated recording storage in GB."
      - name: feature_usage_count
        description: "Total feature usage count."
      - name: unique_participants_hosted
        description: "Number of unique participants hosted."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."

  - name: go_quality_facts
    description: "Aggregated participant quality facts for analytical queries."
    columns:
      - name: quality_fact_id
        description: "Unique identifier for the quality fact record."
        tests: [unique, not_null]
      - name: meeting_id
        description: "Meeting ID."
      - name: participant_id
        description: "Participant ID."
      - name: device_connection_id
        description: "Device connection ID."
      - name: audio_quality_score
        description: "Audio quality score."
      - name: video_quality_score
        description: "Video quality score."
      - name: connection_stability_rating
        description: "Connection stability rating."
      - name: latency_ms
        description: "Estimated latency in milliseconds."
      - name: packet_loss_rate
        description: "Estimated packet loss rate."
      - name: bandwidth_utilization
        description: "Estimated bandwidth utilization in MB."
      - name: cpu_usage_percentage
        description: "Estimated CPU usage percentage."
      - name: memory_usage_mb
        description: "Estimated memory usage in MB."
      - name: load_date
        description: "Date of data load."
      - name: update_date
        description: "Date of last update."
      - name: source_system
        description: "Source system identifier."
