{{ config(severity = 'error') }}

SELECT 
    SUMMARY_DATE,
    ORGANIZATION_ID,
    AVERAGE_MEETING_DURATION
FROM {{ ref('go_daily_meeting_summary') }}
WHERE AVERAGE_MEETING_DURATION < 0 
   OR AVERAGE_MEETING_DURATION > 1440
   OR AVERAGE_MEETING_DURATION IS NULL
